FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

ENV SMQ_CONNECTIONSTRING=Server=(localdb)\MSSQLLocalDB;Database=smq;User Id=smq;Password=smq;
ENV SMQ_KEY=xtPcL81m6tse6LDN/GZgIC6RR+ZEabF+7hhJ32BqehQ=
ENV SMQ_ISSUER=SMQ-Core.com

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

EXPOSE 3002

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "SMQ-Core.dll"]